import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

function formatDate(): string {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export async function generateContractPdf(data: Record<string, string>, templateName: string) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([612, 792]);
  const w = page.getWidth();
  let y = 760;
  const margin = 50;
  const lineHeight = 16;

  const drawText = (text: string, size: number, x: number, opts?: { color?: import('pdf-lib').RGB, font?: import('pdf-lib').PDFFont }) => {
    page.drawText(text, { x, y, size, font: opts?.font || font, color: opts?.color || rgb(0, 0, 0) });
  };

  const wrapText = (text: string, size: number, maxWidth: number): string[] => {
    const words = text.split(' ');
    const lines: string[] = [];
    let current = '';
    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      const width = test.length * size * 0.55;
      if (width > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
    return lines;
  };

  const checkSpace = (needed: number) => {
    if (y - needed < 40) {
      page.drawText(`Page ${pdfDoc.getPageCount()}`, { x: w - 80, y: 20, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
      const newPage = pdfDoc.addPage([612, 792]);
      y = 760;
    }
  };

  // Title
  drawText(templateName, 22, margin, { font: bold });
  y -= 8;
  page.drawLine({ start: { x: margin, y }, end: { x: w - margin, y }, thickness: 1.5, color: rgb(0.2, 0.2, 0.2) });
  y -= 24;

  // Date & ref
  drawText(`Date: ${formatDate()}`, 10, margin, { color: rgb(0.4, 0.4, 0.4) });
  y -= 20;

  // Parties section
  drawText('Parties', 14, margin, { font: bold });
  y -= 18;
  const clientName = data.clientName || data.client_name || 'Client';
  const senderName = 'Contract Creator';
  drawText(`Between: ${senderName} (Freelancer)`, 11, margin);
  y -= 14;
  drawText(`And:    ${clientName} (Client)`, 11, margin);
  y -= 24;

  // Agreement recital
  drawText('Agreement', 14, margin, { font: bold });
  y -= 18;
  const recital = `This agreement is entered into between the Freelancer and the Client for the purpose of engaging the Freelancer's services as described below.`;
  const recitalLines = wrapText(recital, 10, w - margin * 2);
  for (const line of recitalLines) {
    checkSpace(lineHeight);
    drawText(line, 10, margin);
    y -= 14;
  }
  y -= 10;

  // Terms / fields
  drawText('Terms & Scope', 14, margin, { font: bold });
  y -= 20;
  for (const [key, value] of Object.entries(data)) {
    checkSpace(lineHeight);
    const label = key.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').replace(/^./, s => s.toUpperCase());
    drawText(`${label}:`, 11, margin, { font: bold });
    y -= 13;
    const valLines = wrapText(String(value), 10, w - margin * 2);
    for (const line of valLines) {
      checkSpace(lineHeight);
      drawText(line, 10, margin + 12);
      y -= 13;
    }
    y -= 6;
  }

  y -= 10;

  // Signature section
  checkSpace(80);
  page.drawLine({ start: { x: margin, y }, end: { x: margin + 180, y }, thickness: 0.5, color: rgb(0.3, 0.3, 0.3) });
  y -= 4;
  drawText('Freelancer Signature', 9, margin, { color: rgb(0.4, 0.4, 0.4) });
  y -= 36;

  page.drawLine({ start: { x: margin, y }, end: { x: margin + 180, y }, thickness: 0.5, color: rgb(0.3, 0.3, 0.3) });
  y -= 4;
  drawText('Client Signature', 9, margin, { color: rgb(0.4, 0.4, 0.4) });
  y -= 36;

  page.drawLine({ start: { x: margin, y }, end: { x: margin + 180, y }, thickness: 0.5, color: rgb(0.3, 0.3, 0.3) });
  y -= 4;
  drawText('Date', 9, margin, { color: rgb(0.4, 0.4, 0.4) });

  // Footer
  page.drawText(`Generated by SignFlow — ${formatDate()}`, { x: margin, y: 20, size: 8, font, color: rgb(0.5, 0.5, 0.5) });
  page.drawText(`Page ${pdfDoc.getPageCount()}`, { x: w - 60, y: 20, size: 8, font, color: rgb(0.5, 0.5, 0.5) });

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}
